services:

  db:
    image: postgres:16-alpine
    container_name: blackerp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: blackerp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blackerp"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: blackerp-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blackerp
    ports:
      - "8080:8080"

volumes:
  postgres_data:
